#!/usr/bin/with-contenv bash
 shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -zu  69" \
        /usr/sbin/in.tftpd  -L -u abc  ${PORT_RANGE:+--port-range $PORT_RANGE} --secure  /config/www
exec /usr/sbin/in.tftpd  -l --secure -u abc -s /config/www
